export const categories = [
  {
    id: 1,
    img: "/assets/ngbierrq5xurfwquomlj.png",
    title: "Headphones",
    desc: "Discover headphones to start your audiophile journey",
    link: "/collections/headphones",
  },
  {
    id: 2,
    img: "/assets/buaglgtndiwfrmadilzg.jpg",
    title: "DACs & Amps",
    desc: "Discover the widest range of Amps from across the world",
    link: "/collections/dac",
  },
  {
    id: 3,
    img: "/assets/l78toewiyjy5bshcdceg.jpg",
    title: "Speaker Amps",
    desc: "Discover the ultimate listening experience with Speaker Amps.",
    link: "/collections/speaker-amplifiers",
  },
];

export const carouselData = [
  {
    id: 0,
    type: "dark",
    img: "/assets/vhcuurhvwsnxczzdopsf.jpg",
    img_mobile: "/assets/miiehccuaozbn8rr6qrm.jpg",
    subtitle: "New Arrivals",
    title: "<b>COLORFLY</b><br>CDA-M2",
    desc: "Dual CS43198 Portable USB DAC/AMP",
    link: "/products/colorfly-cda-m2-dual-cs43198-portable-usb-dac-amp",
    buttontext: "SHOP NOW",
    footer: "COLORFLY CO.",
  },
  {
    id: 1,
    type: "dark",
    img: "/assets/idilrrxtt5nom1v3w8gb.jpg",
    img_mobile: "/assets/gomzgtoic490k46nxc2n.jpg",
    subtitle: "New Arrivals",
    title: "<b>TRUTHEAR</b><br>NOVA 1DD & 4BA",
    desc: "3-way Crossover Composite Structure",
    link: "/products/truthear-nova-1dd-4ba-in-ear-headphone",
    buttontext: "SHOP NOW",
    footer: "TRUTHEAR CO.",
  },
  {
    id: 2,
    type: "dark",
    img: "/assets/khcju5y0xzj6gg8fg8hc.jpg",
    img_mobile: "/assets/fmbbgixxsskajcghuvab.jpg",
    subtitle: "New Arrivals",
    title: "<b>TOPPING</b><br>D70 Pro & A70 Pro",
    desc: "ESS ES9039SPRO DAC",
    link: "/products/topping-d70pro-sabre-dac-es9039spro-xu316-bluetooth-5-1-ldac-aptx-adaptive-hifi-decoder",
    buttontext: "SHOP NOW",
    footer: "TOPPING CO.",
  },
  {
    id: 3,
    type: "light",
    img: "/assets/x7vv4fmwamko5xnyajlv.jpg",
    img_mobile: "/assets/jbbevgngtswk3ak3nsh1.jpg",
    subtitle: "New Arrivals",
    title: "<b>MOONDROP</b><br>BLESSING 3",
    desc: "2DD+4BA Hybrid Crossover",
    link: "/products/moondrop-blessing3-earphone-2dd-4ba-hybrid-in-ear-monitors-triple-frequency-division-headphone-1",
    buttontext: "SHOP NOW",
    footer: "MOONDROP CO.",
  },
  {
    id: 4,
    type: "dark",
    img: "/assets/w2suskieg31xe0fjmsu5.jpg",
    img_mobile: "/assets/lo59vwmym8i3gxzjdtqk.jpg",
    subtitle: "New Arrivals",
    title: "<b>TRUTHEAR x Crinacle</b><br>ZERO:RED",
    desc: "Dual Dynamic Drivers In-Ear Headphone",
    link: "/products/truthear-x-crinacle-zero-red-dual-dynamic-drivers-in-ear-headphone",
    buttontext: "SHOP NOW",
    footer: "TRUTHEAR CO.",
  },
];
